# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/pinpt/httpclient"
  version = "2.0.0"

[[constraint]]
  name = "github.com/oliveagle/jsonpath"
  branch = "master"

[[override]]
  name = "gopkg.in/confluentinc/confluent-kafka-go.v1"
  version = "1.1.0"

[[constraint]]
  name = "github.com/cespare/xxhash"
  version = "v2.0.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  source = "github.com/pinpt/websocket"
  branch = "httpsproxy"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.4"

[[constraint]]
  name = "github.com/bsm/redislock"
  version = "0.3.0"
