version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/pinpt/go-common

    environment:
      TEST_RESULTS: /tmp/test-results
      kafkaversion: v1.1.0
      PATH: ~/.pinpoint:$PATH

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run: bash -c "$(curl -sSL https://raw.githubusercontent.com/pinpt/pinpoint/master/install.sh)"
      - run: echo $PATH
      - run: pinpoint build start

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Install librdkafka
          command: |
            if [ ! -f  /go/pkg/librdkafka.so ];
            then
              sudo apt-get install libsasl2-2
              cd /tmp
              git clone https://github.com/edenhill/librdkafka.git
              cd librdkafka
              git fetch && git fetch --tags
              echo building $kafkaversion
              git checkout $kafkaversion
              ./configure --prefix /
              make && sudo make install
              mkdir -p /go/pkg
              cp /lib/librdkafka.so* /go/pkg
            else
              echo "already installed"
            fi

      - run: go get github.com/golang/dep/cmd/dep
      - run: go get github.com/jstemmer/go-junit-report
      - run: make dependencies

      - run:
          name: Run unit tests
          command: |
            make test | tee ${TEST_RESULTS}/go-test.out
            set +e
            grep "\-\-\- FAIL:" ${TEST_RESULTS}/go-test.out
            if [ $? -eq 0 ];
            then
              echo "Some test cases failed"
              exit 1
            else
              echo "All tests passed"
              set -e
              go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml
              exit 0
            fi

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

      - run: pinpoint build finish --dry-run